# Generated by Django 5.0.1 on 2024-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
